[phases.setup]
nixPkgs = ["nodejs", "python311", "python311Packages.pip"]
aptPkgs = ["python3.11", "python3-pip"]

[phases.install]
cmds = ["npm ci", "pip3 install --user -r backend/requirements.txt"]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "python3 backend/api_server.py"