[phases.setup]
nixPkgs = ["nodejs", "python311", "python311Packages.pip"]

[phases.install]
cmds = ["rm -rf node_modules/.cache", "npm ci", "pip3 install --break-system-packages -r backend/requirements.txt"]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "python3 backend/api_server.py"