[phases.setup]
nixPkgs = ["nodejs", "npm", "python311", "python311Packages.pip"]

[phases.install]
cmds = ["npm ci", "pip install -r backend/requirements.txt"]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "python3 backend/api_server.py"